package com.mhdsys.competition.management.web.constants;

/**
 * @author DELL
 */
public class CompetitionManagementWebPortletKeys {

	public static final String MHDSYS_COMPETITION_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysCompetitionManagementWebPortlet";
	public static final String MHDSYS_COMPETITION_INITIATION_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysCompetitionInitiationManagementWebPortlet";
	public static final String MHDSYS_COMPETITION_INITIATION_LIST_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysCompetitionInitiationListManagementWebPortlet";

	public static final String MHDSYS_COMPETITION_PT_TEACHER_REQUEST_LIST_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysCompetitionPTTEacherRequestListManagementWeb";
	public static final String MHDSYS_COMPETITION_PRINCIPAL_APPROVED_LIST_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysCompetitionPrincipalApprovedListManagementWeb";
	public static final String MHDSYS_COMPETITION_SCHEDULED_LIST_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysCompetitionScheduledListManagementWeb";
	public static final String MHDSYS_UPLOADED_RESULT_LIST_MANAGEMENTWEB = "com_mhdsys_competition_management_web_MhdsysUploadedResultListManagementWeb";

	public static final String CREATE_COMPETITION_MASTER_MVC_RENDER_COMMAND = "CreateCompetitionMasterMVCRenderCommand";

	public static final String SAVE_COMPETITION_MASTER_MVC_RESOURCE_COMMAND = "SaveCompetitionMasterMVCResourceCommand";

	public static final String COMPETITION_INITIATION_MVC_RENDER_COMMAND = "CompetitionInitiationMVCRenderCommand";
	public static final String SAVE_COMPETITION_INITIATION_MVC_RESOURCE_COMMAND = "SaveCompetitionInitiationMVCResourceCommand";
	public static final String SAVE_COMPETITION_SCHEDULE_MVC_RESOURCE_COMMAND = "SaveCompetitionScheduleMVCResourceCommand";
	public static final String COMPETITION_INITIATION_LIST_MVC_RENDER_COMMAND = "CompetitionInitiationListMVCRenderCommand";
	public static final String SAVE_COMPETITION_PT_TEACHER_MVC_RESOURCE_COMMAND = "SavePTTeacherApplicationMVCResourceCommand";
	public static final String PT_TEACHER_APPLICATION_FORM_MVC_RENDER_COMMAND = "PTTeacherApplicationMVCRenderCommand";
	public static final String VIEW_PT_TEACHER_APPLICATION_FORM_MVC_RENDER_COMMAND = "ViewPtTeacherApplicationFormMVCRenderCommand";
	public static final String SAVE_PRINCIPAL_APPROVE_MVC_RESOURCE_COMMAND = "SavePrincipalApproveMVCResourceCommand";
	public static final String ADD_COMPETITION_SCHEDULE_MVC_RENDER_COMMAND = "AddCompetitionScheduleMVCRenderCommand";
	public static final String SMART_SEARCH_PARTICIPANT_MVC_RESOURCE_COMMAND = "SmartSearchParticipantMVCResourceCommand";
	public static final String RESULT_UPLOAD_MVC_RENDER_COMMAND = "ResultUploadMVCRenderCommand";
	public static final String SAVE_RESULT_UPLOAD_MVC_RESOURCE_COMMAND = "SaveResultUploadMVCResourceCommand";

}